### PR TITLE
Unexpected concurrent behavior

### PR DESCRIPTION
**Pull request by veqryn**

### CODE REVIEW

**Comment by osklyar** [comment]
Concurrent as in fire-and-forget even on a single handler: I do not want my app to wait for the handle to complete logging the entry. The side effect is exactly the one that you mention: console apps may miss some entries at the end. So flipping the flag could be ok, but changing to a wait for completion would defy the purpose of putting it in (to a large extent at least).

**Comment by veqryn** [comment]
My concern is not just short little console apps, but also long running processes. If there is a panic or the process is killed, or a bad state is entered which triggers some shutdown hooks, those last few log lines are the most important, as they often hold the information needed to debug why the process died or the context leading up to the panic.  If those don't get printed, you are SOL.

But I also understand your concern: there could be handlers that for example are logging to Slack, which could take a whole minute to return and complete.  You don't want to wait on that.

Hm... I wonder if there is a way to have your cake and eat it too. Maybe a setting on each handler on whether we should wait for it or not?  If you like this idea, I could improve this PR...

**Comment by osklyar** [comment]
So for the moment we could do with flipping the concurrent switch to false. The other change about synchronising the handlers would need more thought.

**Comment by veqryn** [comment]
Ok, I have the smaller change here: https://github.com/ventu-io/slog/pull/8

We can think about and extend this current PR to handle synchronising handlers at a later date.

**Comment by osklyar** [comment]
Please move to a local branch and we will address it later (#8 excluded, see the comment there).

**Pull request closed without merging**
